In [ ]:
"""
1.Diagonal shows how many abstract is fetched from a particuler protein.(this is due to input,this can varry according to the input that we have taken)
2.upper right and lower right triangle are not yet combined i.e. it is a directed graph matrix.
3.Due to shortage of time , Csv file is not generatable right now although you can see the output.
4.To be added : csv generator for later function.

"""

In [43]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import treebank
##################################################################
df1 = pd.read_csv("input.csv")
pname=df1['PROTEIN_NAME'].drop_duplicates().values.tolist()
#def function1(protein_list):
def function1():
    "Searching all the proteins"
    df1 = pd.read_csv("input.csv")
    print('Loaded')
    #print(df1)
    protein_list = df1['PROTEIN_NAME'].drop_duplicates().values.tolist()
    #print(protein_list)
    length=(len(protein_list))
    #print(length)
    Matrix = [[0 for x in range(length)] for y in range(length)]
    for protein in protein_list:
        spe_protein = df1.loc[df1['PROTEIN_NAME'] == protein] #Selecting dataframe of specific Protein
        a = spe_protein.ABSTRACT.str.cat(sep=', ')            #Combining Column of all the protein
        #print(a)
        #print(protein)
        tokens = nltk.word_tokenize(a)
        tagged = nltk.pos_tag(tokens)
        #print(tokens)
        for i in tagged:
            if(i[1]=='NNP') and (i[0] in protein_list):
                #print(i[0],end=' ')
                #print(i[0] in protein_list)
                row = protein_list.index(protein)
                col = protein_list.index(i[0])
                #row = protein and col = frequent
                Matrix[row][col]+=1
                
    #print(Matrix)
    
    
    print('    ', end='', flush=True)
    print(pname)
    t=0
    print('')
    for x in Matrix:
        print(pname[t]+"    ", end='', flush=True)
        print(*x, sep="       ")
        t+=1
        print('')
    

                        
##################################################################
function1()

Loaded
    ['A13', 'B84', 'C90', 'D77', 'E999', 'F010', 'G234', 'H789', 'I900']

A13    3       2       2       1       0       0       0       0       0

B84    1       1       0       0       0       0       0       0       0

C90    0       0       1       1       0       0       0       0       0

D77    2       0       0       3       0       0       1       1       1

E999    0       0       0       0       2       0       1       2       0

F010    3       3       2       0       0       6       2       2       0

G234    2       1       2       2       0       0       6       1       0

H789    4       3       1       0       0       0       0       7       0

I900    2       2       0       0       0       4       0       5       5

In [30]:
pname

['A13', 'B84', 'C90', 'D77', 'E999', 'F010', 'G234', 'H789', 'I900']

In [ ]:
spe

In [44]:
protein = 'A13'
df1.loc

   PROTEIN_NAME  UID                         ABSTRACT
0           A13  111                   A13 , B84 ,C90
1           A13  112                        A13 , C90
2           A13  113                   A13, B84 , D77
3           B84  114                        B84 , A13
4           C90  115                        C90 , D77
5           D77  116  D77 , A13 ,I900 , J, H789 ,G234
6           D77  117                              D77
7           D77  118                         D77 ,A13
8          E999  119               E999 , G234 , H789
9          E999  120                       E999 ,H789
10         F010  121       F010 ,A13 ,B84 , C90, G234
11         F010  122       F010 ,A13 ,B84 , C90, G234
12         F010  123                   F010 ,A13 ,B84
13         F010  124                             F010
14         F010  125                      F010 , H789
15         F010  126                      F010 , H789
16         G234  127                             G234
17         G234  128                             G234
18         G234  129                             G234
19         G234  130      G234 , A13, B84 , C90 , D77
20         G234  131                  G234 , A13, D77
21         G234  132                  G234 ,C90 ,H789
22         H789  133                             H789
23         H789  134                             H789
24         H789  135                             H789
25         H789  136                        H789, A13
26         H789  137                  H789, A13 , B84
27         H789  138             H789, A13 , B84 ,C90
28         H789  139                  H789, A13 , B84
29         I900  140                        I900,H789
30         I900  141                I900 , F010 ,H789
31         I900  142   I900 , F010 ,H789 , B84 , A13
32         I900  143      I900 , F010 ,H789 ,A13 ,B84
33         I900  144                I900 , F010 ,H789